In [12]:
df

,dossier,image
0,"Acacia dealbata Link, 1822",C:/Users/utilisateur/Desktop/projet chef-d'oeu...
1,"Acacia dealbata Link, 1822",C:/Users/utilisateur/Desktop/projet chef-d'oeu...
2,"Acacia dealbata Link, 1822",C:/Users/utilisateur/Desktop/projet chef-d'oeu...
3,"Acacia dealbata Link, 1822",C:/Users/utilisateur/Desktop/projet chef-d'oeu...
4,"Acacia dealbata Link, 1822",C:/Users/utilisateur/Desktop/projet chef-d'oeu...
...,...,...
12993,"Womersleyella setacea (Hollenb.) R.E. Norris, ...",C:/Users/utilisateur/Desktop/projet chef-d'oeu...
12994,"Womersleyella setacea (Hollenb.) R.E. Norris, ...",C:/Users/utilisateur/Desktop/projet chef-d'oeu...
12995,"Womersleyella setacea (Hollenb.) R.E. Norris, ...",C:/Users/utilisateur/Desktop/projet chef-d'oeu...
12996,"Womersleyella setacea (Hollenb.) R.E. Norris, ...",C:/Users/utilisateur/Desktop/projet chef-d'oeu...
12997,"Womersleyella setacea (Hollenb.) R.E. Norris, ...",C:/Users/utilisateur/Desktop/projet chef-d'oeu...

In [2]:
y = df.dossier
X = df.image

In [13]:
df2

,Unnamed: 0,Nom de référence,Nom vernaculaire,Statut*,Règne,Classe,Ordre,Famille,CD_REF,CD_NOM
0,NaN,"Acacia dealbata Link, 1822","Mimosa argenté, Mimosa des fleuristes, Mimosa ...",J,Plantae (Plantes),"Equisetopsida (Plantes terrestres, Embryophyte...",Fabales,Fabaceae,79691,79691
1,NaN,"Acacia mearnsii De Wild., 1925","Mimosa argenté, Mimosa vert",J,Plantae (Plantes),"Equisetopsida (Plantes terrestres, Embryophyte...",Fabales,Fabaceae,79700,79700
2,NaN,"Acacia saligna (Labill.) H.L.Wendl., 1820","Mimosa à feuilles de Saule, Mimosa à feuilles ...",J,Plantae (Plantes),"Equisetopsida (Plantes terrestres, Embryophyte...",Fabales,Fabaceae,79710,79710
3,NaN,"Acer negundo L., 1753","Érable negundo, Érable frêne, Érable Négondo",J,Plantae (Plantes),"Equisetopsida (Plantes terrestres, Embryophyte...",Sapindales,Sapindaceae,79766,79766
4,NaN,"Acrothamnion preissii (Sonder) E.M.Wollaston, ...",Acrochaetium de Preiss,J,Plantae (Plantes),Florideophyceae,Ceramiales,Ceramiaceae,369355,369355
...,...,...,...,...,...,...,...,...,...,...
60,NaN,"Spartina alterniflora Loisel., 1807",Spartine à feuilles alternes,J,Plantae (Plantes),"Equisetopsida (Plantes terrestres, Embryophyte...",Poales,Poaceae,124424,124424
61,NaN,"Spiraea x billardii Hérincq, 1857",Spirée,J,Plantae (Plantes),"Equisetopsida (Plantes terrestres, Embryophyte...",Rosales,Rosaceae,124682,124682
62,NaN,"Sporobolus indicus (L.) R.Br., 1810","Sporobole fertile, Sporobole tenace",J,Plantae (Plantes),"Equisetopsida (Plantes terrestres, Embryophyte...",Poales,Poaceae,124719,124719
63,NaN,"Symphyotrichum lanceolatum (Willd.) G.L.Nesom,...",Aster lancéolé,J,Plantae (Plantes),"Equisetopsida (Plantes terrestres, Embryophyte...",Asterales,Asteraceae,125330,125330
64,NaN,"Womersleyella setacea (Hollenb.) R.E. Norris, ...",Vomersleyelle sétacée,J,Plantae (Plantes),Florideophyceae,Ceramiales,Rhodomelaceae,370833,370833

In [5]:
import PIL.Image
import matplotlib.pyplot as plt
import numpy as np

im = PIL.Image.open(X[1])

In [4]:
from sklearn.model_selection import train_test_split

In [ ]:
import matplotlib.pyplot as plt
import keras
from sklearn.metrics import confusion_matrix
import itertools
import tensorflow as tf
import seaborn as sns


CNN1 = keras.Sequential()
CNN1.add(keras.layers.Conv2D(32, kernel_size=(3,3), activation='relu', strides=(1,1)))
CNN1.add(keras.layers.Flatten())
CNN1.add(keras.layers.Dense(64, activation='relu'))
CNN1.add(keras.layers.Dense(6, activation='softmax'))
 
CNN1.compile(optimizer=keras.optimizers.Adam(lr=1e-3), loss='sparse_categorical_crossentropy',metrics='accuracy')
 
history = CNN1.fit(x_train, y_train, epochs=10, batch_size=100, validation_split=0.33)
    
print("Test evaluation")
CNN1.evaluate(x_test, y_test)

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']
epochs = range(1, len(acc) + 1)

plt.plot(epochs, acc, 'bo', label='Training acc')
plt.plot(epochs, val_acc, 'b', label='Validation acc')
plt.title('Training and validation accuracy')
plt.legend()
plt.figure()
plt.plot(epochs, loss, 'bo', label='Training loss')
plt.plot(epochs, val_loss, 'b', label='Validation loss')
plt.title('Training and validation loss')
plt.legend()
plt.show()

y_pred=CNN1.predict_classes(x_test)
con_mat = tf.math.confusion_matrix(labels=y_test, predictions=y_pred).numpy()
con_mat_norm = np.around(con_mat.astype('float') / con_mat.sum(axis=1)[:, np.newaxis], decimals=2)
con_mat_df = pd.DataFrame(con_mat_norm,
                     index = class_names, 
                     columns = class_names)
  
figure = plt.figure(figsize=(8, 8))
sns.heatmap(con_mat_df, annot=True,cmap=plt.cm.Blues)
plt.tight_layout()
plt.ylabel('True label')
plt.xlabel('Predicted label')
plt.show()